Smoke tests with resource quotas
stackabletech/kafka-operator pull request #595
Opened 2023-06-06 13:43 UTC by razvan

# Description

Part of: https://github.com/stackabletech/issues/issues/394

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

2023-06-29 14:17 UTC, sbernauer requested changes
Only minor stuff

2023-06-29 14:17 UTC, sbernauer commented on docs/modules/kafka/pages/usage-guide/storage-resources.adoc
> +* `4Gi` allocated PVs
```suggestion
* `4Gi` persistent storage
```

2023-06-29 14:17 UTC, sbernauer commented on docs/modules/kafka/pages/usage-guide/storage-resources.adoc
> +      replicas: 2
I would not mention that here, as we default to a single replica
```suggestion
```

2023-06-29 14:17 UTC, sbernauer commented on tests/templates/kuttl/configuration/20-install-kafka.yaml.j2
>            # Inherit the default value '500m' set by the operator
```suggestion
          # Inherit the default value '250m' set by the operator
```

2023-06-29 14:17 UTC, sbernauer commented on tests/templates/kuttl/configuration/20-install-kafka.yaml.j2
>            # Override the default value '4' set by the operator
```suggestion
          # Override the default value '1' set by the operator
```

2023-06-29 14:17 UTC, sbernauer commented on tests/templates/kuttl/configuration/20-install-kafka.yaml.j2
>                # Inherit the default value '500m' set by the operator
```suggestion
              # Inherit the default value '250m' set by the operator
```

2023-06-29 14:41 UTC, sbernauer approved these changes
Thanks! LGTM when tests pass

2023-06-30 11:14 UTC, maltesander commented
Trying azure:
https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/kafka-operator-it-custom/43/

2023-06-30 13:32 UTC, maltesander commented
bors merge

2023-06-30 13:40 UTC, closed without merging