New version 3.4.1, 3.5.0
stackabletech/kafka-operator pull request #627
Opened 2023-10-10 15:40 UTC by maltesander

# Description

- added support for versions 3.4.1, 3.5.0
- removed support for versions 2.7.1, 3.1.0, 3.2.0, 3.3.1

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
- [ ] Changes need to be "offline" compatible
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

2023-10-17 11:48 UTC, siegfriedweber commented on CHANGELOG.md
```diff
- - `vector` `0.26.0` -> `0.31.0` ([#612]).
+ - `vector` `0.26.0` -> `0.33.0` ([#612], [#627]).
```

2023-10-18 07:34 UTC, maltesander commented
test: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/kafka-operator-it-custom/51/

2023-10-19 09:55 UTC, adwk67 requested changes
Just one small thing, othwerwise all good!

2023-10-19 09:55 UTC, adwk67 commented on CHANGELOG.md
> +- Support new versions 3.4.1, 3.5.1 ([#627]).
```suggestion
- Support new versions 2.8.2, 3.4.1, 3.5.1 ([#627]).
```

2023-10-19 10:05 UTC, adwk67 approved these changes
LGTM!

2023-10-19 10:31 UTC, merged